### ISSUE TITLE
Zen30 double plug does not control the lower, relay button via zwave

### ISSUE THREAD

**Issue by appmyhome** [koktail-nl/com.getzooz.issues#17] opened 2024-02-26 23:31 UTC
**Describe the bug**

The multichannel function you added works great. But since updating to the latest version the lower button which was used as a relay/on/off function no longer works. We have the upper paddle as multifunction but the relay switch is just for power. Now I can only operate the relay button manually, no wave command will control it.

**To Reproduce**
install the switch with the upper paddle as multifunction only. wire the relay button to control power to a light. install the prior zooz driver. switch will work as expected, but update to your current version and the relay button can no longer be controlled via zwave. 

**Expected behavior**
the relay button should turn the light on or off via Z-wave. now only with a button push.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] latest iOS.
 - Browser [e.g. chrome, safari] latest safari
behavior happens via the desktop or iPhone

**Smartphone (please complete the following information):**

**Additional context**
thank you, Mark

**Comment by koktaildotcom** [comment] 2024-03-21 15:15
The `relay button` is now exposed as multi channel node and when you are repairing the device you should get a separate device to control the replay outputs.

**Comment by appmyhome** [comment] 2024-03-21 16:18
Hi

Thank you for updating.

The app still shows 1.0.4. So the device still shows as before. And I do not see a repair offering.

Do you know when Athom will approve your update?

Thank you
Mark

**Comment by appmyhome** [comment] 2024-03-25 23:24
Hi

On a related note. I notice that the install process for all Zoom switches says press 3 times on the upper paddle first, which is the exclusion process, but Zooz directions say press the lower paddle for the exclusion, Then for inclusion press the upper paddle 3 times. Not sure if you have control of those messages, but it does make a difference. I just installed a new Zen76 and until I pressed the lower paddle the pairing would not complete.

Hope this is helpful.

Thank you
Mark

PS: any update on when Athom will approve your Zen30 fix?

**Comment by appmyhome** [comment] 2024-04-20 00:22
Hi

I uninstalled the Zen30 and reinstalled. After some trials getting it to pair I notice you now make two switches. The new switch seems to be the rely however it does not work. You get the "Missing Capability Listener: onoff”
Error.

Ideas?

Thank you
Mark

**Comment by koktaildotcom** [comment] 2024-05-01 09:10
Its most likely an issue with the implementation change with the 800 series chip. I cannot reproduce this issue with my device (700 series chip).

**Comment by koktaildotcom** [comment] 2024-05-02 07:06
I will ask for the 800 series so that we can integrate them too.

**Comment by appmyhome** [comment] 2024-05-02 19:58
Good to hear, thank you. 

If you need me to test on ours just let me know.

Thank you
Mark

**Comment by kamilio** [comment] 2024-05-04 00:41
I have the same problem on all my ZEN30 switches (I have around 5) also reported this problem to Zooz, they managed to reproduce. It would be great to get this fixed.

**Comment by koktaildotcom** [comment] 2024-09-06 12:45
I fixed a bug, the child device was on the wrong cluster endpoint it will be fixed in: 1.0.13 (https://homey.app/a/com.getzooz/test)

**Closed as completed by koktaildotcom** 2024-09-06 12:45 UTC
Labels: bug

**Comment by appmyhome** [comment] 2024-09-27 18:46
FYI, the Zooz Zen 30 now works!!!!!

Thank you
Mark

**Comment by kamilio** [comment] 2024-10-06 22:14
Hi @koktaildotcom,

I tried fixing the device without unpairing/pairing it and ran into an issue, [similar to changing to light](https://github.com/koktail-nl/com.getzooz.issues/issues/22#issuecomment-2395596739) in other thread. The device has the `data` field, which is supposedly immutable. The `multiChannelNodeId` is stored in the data and can't be changed. 

This is the fix btw
```js
device.class = "socket";
device.virtualClass = "fan";
device.settings.zw_device_class_generic = 'GENERIC_TYPE_SWITCH_BINARY';
device.settings.zw_node_id = device.settings.zw_node_id.split('.')[0] + '.2';

await Homey.devices.setDeviceSettings({ id: device.id, settings: device.settings });
await Homey.devices.updateDevice({ id: device.id, device });
```

Unless the zwave driver implicitly uses this `multiChannelNodeId` from `data` storage, I recommend hardcoding it in the class definition or somewhere. It will always be 2, so there's no reason to have it stored in data. 

If you were to change it and release new version, the fix script might work.
